services:
  nats:
    image: nats:2.10-alpine
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - nats-data:/var/lib/nats
    environment:
      - NATS_USER=nats
      - NATS_PASS=nats
    networks:
      - certstream-network

  certstream:
    image: 0rickyy0/certstream-server-go:latest
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      nats:
        condition: service_healthy
    networks:
      - certstream-network

  certstream-scout:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ctlog_data:/app/ctlog_data
    env_file:
      - .env
    depends_on:
      nats:
        condition: service_healthy
      certstream:
        condition: service_healthy
    networks:
      - certstream-network

networks:
  certstream-network:
    driver: bridge

volumes:
  nats-data:
    driver: local